[project]
name = "jwks-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=46.0.4",
    "flask>=3.1.2",
    "pyjwt>=2.11.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.0",
]
